/* Project queries */


/* Report 1 – Vehicles currently in a given parking lot*/

SELECT MAKE, MODEL, PERMITID
FROM CAR JOIN PARKINGLOCATION
ON CAR.PARKINGNAME = PARKINGLOCATION.PARKINGNAME
WHERE CAR.PARKINGNAME = 'Lot A' ;

/* I noticed that report 1 had a total current cars for for Lot A so I also made the below query to pull the total count*/
SELECT CAR.PARKINGNAME, COUNT(VIN#) AS TOTAL_CURRENT_CARS
FROM CAR, PARKINGLOCATION
WHERE CAR.PARKINGNAME = PARKINGLOCATION.PARKINGNAME AND PARKINGLOCATION.PARKINGNAME = 'Lot A'
GROUP BY CAR.PARKINGNAME;

/* Report 2 – List of lots with current cars and capacity*/

SELECT CAR.PARKINGNAME, COUNT(VIN#) AS VEHICLES_CURRENTLY_IN_LOT, CAPACITY-COUNT(VIN#) AS OPEN_SPACES
FROM CAR, PARKINGLOCATION
WHERE CAR.PARKINGNAME = PARKINGLOCATION.PARKINGNAME
GROUP BY CAR.PARKINGNAME, CAPACITY;

/* Report 3 – Outstanding parking violation tickets*/
/* firstname, lastname, permit#, permit_type,licenseplate, # of notifications sent */

SELECT PERMITHOLDER.FIRSTNAME, PERMITHOLDER.LASTNAME,PERMIT.PERMITID, PERMITHOLDER.OCCUPATION, CAR.PLATE#, NOTIFICATION.NOTIFICATIONCOUNT AS NOTIFICATIONS_SENT
FROM PERMITHOLDER
RIGHT JOIN PERMIT
ON PERMITHOLDER.DL# = PERMIT.DL#
RIGHT JOIN CAR
ON PERMIT.PERMITID = CAR.PERMITID
RIGHT JOIN NOTIFICATION
ON NOTIFICATION.DL# = PERMITHOLDER.DL#
GROUP BY PERMITHOLDER.FIRSTNAME, PERMITHOLDER.LASTNAME,PERMIT.PERMITID, PERMITHOLDER.OCCUPATION, CAR.PLATE#, NOTIFICATION.NOTIFICATIONCOUNT;


/* Report 4 – Parking violation ticket history by status – viewed for a given date range*/
SELECT OCCUPATION, COUNT(CASE WHEN TICKET.AMOUNT_PAID - VIOLATION.FINEAMOUNT < 0 THEN 1 ELSE NULL END) AS NUMBER_OF_UNPAID_TICKETS, COUNT(CASE WHEN TICKET.AMOUNT_PAID - VIOLATION.FINEAMOUNT >= 0 THEN 1 ELSE NULL END) AS NUMBER_OF_PAID_TICKETS, MAX(CASE WHEN TICKET.AMOUNT_PAID - VIOLATION.FINEAMOUNT < 0 THEN VIOLATION.FINEAMOUNT ELSE 0 END) AS MAX_AMOUNT_OF_OUTSTANDING_TICKET
FROM PERMITHOLDER
RIGHT JOIN PERMIT
ON PERMITHOLDER.DL# = PERMIT.DL#
RIGHT JOIN TICKET
ON PERMIT.PERMITID = TICKET.PERMITID
RIGHT JOIN VIOLATION
ON TICKET.CITATION# = VIOLATION.CITATION#
WHERE TICKET.TICKETISSUE BETWEEN TO_DATE('2019-JAN-01', 'YYYY-MON-DD') AND TO_DATE('2019-JAN-31', 'YYYY-MON-DD')
GROUP BY OCCUPATION, TICKET.AMOUNT_PAID, VIOLATION.FINEAMOUNT;
  

/* Report 5 – Personal Profiles*/

SELECT FIRSTNAME, LASTNAME, EMAIL, OCCUPATION AS PERMIT_TYPE, COUNT(TICKET.CITATION#) AS NUMBER_OF_TICKETS
FROM PERMITHOLDER
RIGHT JOIN PERMIT
ON PERMITHOLDER.DL# = PERMIT.DL#
RIGHT JOIN TICKET
ON PERMIT.PERMITID = TICKET.PERMITID
GROUP BY FIRSTNAME, LASTNAME, OCCUPATION, EMAIL;


/* Report 6 – Permits issued by semester*/

SELECT
	CASE 
		WHEN EXTRACT(MONTH FROM DATESTART)>=3 AND EXTRACT(MONTH FROM DATESTART)<=5 
			THEN CONCAT('SPRING-',EXTRACT(YEAR FROM DATESTART))
		WHEN EXTRACT(MONTH FROM DATESTART)>=6 AND EXTRACT(MONTH FROM DATESTART)<=8 
			THEN CONCAT('SUMMER-',EXTRACT(YEAR FROM DATESTART))
		WHEN EXTRACT(MONTH FROM DATESTART)>=9 AND EXTRACT(MONTH FROM DATESTART)<=11 
			THEN CONCAT('AUTUMN-',EXTRACT(YEAR FROM DATESTART))
		ELSE CONCAT('WINTER-',EXTRACT(YEAR FROM DATESTART))
	END AS "SEMESTER",
count(PERMITID) AS NUMBER_OF_PERMITS
FROM PERMIT
GROUP BY CASE 
			WHEN EXTRACT(MONTH FROM DATESTART)>=3 AND EXTRACT(MONTH FROM DATESTART)<=5 
				THEN CONCAT('SPRING-',EXTRACT(YEAR FROM DATESTART))
			WHEN EXTRACT(MONTH FROM DATESTART)>=6 AND EXTRACT(MONTH FROM DATESTART)<=8 
				THEN CONCAT('SUMMER-',EXTRACT(YEAR FROM DATESTART))
			WHEN EXTRACT(MONTH FROM DATESTART)>=9 AND EXTRACT(MONTH FROM DATESTART)<=11 
				THEN CONCAT('AUTUMN-',EXTRACT(YEAR FROM DATESTART))
			ELSE CONCAT('WINTER-',EXTRACT(YEAR FROM DATESTART))
		END;

/* Report 7 – Active Permits by Type*/
SELECT OCCUPATION AS PERMIT_TYPE, COUNT(PERMIT.PERMITID) AS PERMIT_AMOUNT
FROM PERMITHOLDER
JOIN PERMIT
ON PERMITHOLDER.DL# = PERMIT.DL#
GROUP BY OCCUPATION;
